//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalReportMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMenu
    {
        public int id { get; set; }
        public Nullable<int> idCustomer { get; set; }
        public Nullable<int> idMenu { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
